In [1]:
from numpy import *
import matplotlib.pyplot as plt
def loadDataSet(filename):
    dataMat=[]
    labelMat=[]
    fr = open('testSet.txt')
    for line in fr.readlines():
        lineArr = line.strip().split()
        dataMat.append([float(lineArr[0]), float(lineArr[1])])
        labelMat.append(int(lineArr[2]))
    return dataMat,labelMat
def selectJrand(i,m):
    j=i
    while (j==i):
        j = int(random.uniform(0,m))
    return j
def clipAlpha(aj,H,L):
    if aj > H:
                aj=H
    if L > aj:
                aj=L
    return  aj


In [2]:
dataArr,labelArr = loadDataSet('testSet.txt')
labelArr

[-1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 1,
 -1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 -1,
 -1,
 1,
 1,
 1,
 -1,
 1,
 1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 1,
 -1,
 1,
 1,
 1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1,
 -1]

In [3]:
dataMatrix = mat(dataArr)
print(dataMatrix.T)

[[ 3.542485e+00  3.018896e+00  7.551510e+00  2.114999e+00  8.127113e+00
   7.108772e+00  8.610639e+00  2.326297e+00  3.634009e+00  3.413670e-01
   3.125951e+00  2.123252e+00  8.878350e-01  7.139979e+00  1.696414e+00
   8.117032e+00  8.497162e+00  4.658191e+00  8.197181e+00  1.208047e+00
   1.928486e+00  2.175808e+00  7.886608e+00  3.223038e+00  3.628502e+00
   7.407860e+00  7.286357e+00  2.301095e+00 -2.325420e-01  3.457096e+00
   3.023938e+00  8.015003e+00  8.991748e+00  7.916831e+00  7.616862e+00
   2.450939e+00  7.270337e+00  1.749721e+00  1.803111e+00  8.804461e+00
   1.231257e+00  2.074915e+00 -7.430360e-01  3.536555e+00  8.410143e+00
   7.382988e+00  6.960661e+00  8.234460e+00  8.168618e+00  1.534187e+00
   9.229518e+00  7.886242e+00  2.893743e+00  1.870457e+00  5.286862e+00
   6.080573e+00  2.544314e+00  6.016004e+00  9.263100e-01  8.702960e-01
   2.369345e+00  1.363782e+00  7.279460e+00  1.896005e+00  8.102154e+00
   2.529893e+00  1.963874e+00  8.132048e+00  8.245938e+00  6.543

In [4]:
data = mat(labelArr).transpose()
a= mat(zeros((100,1)))
print(labelArr)

[-1, -1, 1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, -1, -1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, 1, -1, -1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, 1, -1, -1, -1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1]


In [5]:
multiply(data,a).T

matrix([[-0., -0.,  0., -0.,  0.,  0.,  0., -0., -0., -0., -0., -0., -0.,
          0., -0.,  0.,  0., -0.,  0., -0., -0., -0.,  0., -0., -0.,  0.,
          0., -0., -0., -0., -0.,  0.,  0.,  0.,  0., -0.,  0., -0., -0.,
          0., -0., -0., -0., -0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,
         -0., -0.,  0.,  0., -0.,  0., -0., -0., -0., -0.,  0., -0.,  0.,
         -0., -0.,  0.,  0.,  0., -0.,  0.,  0., -0., -0.,  0., -0.,  0.,
          0.,  0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,  0., -0.,  0.,
          0.,  0., -0., -0., -0., -0., -0., -0., -0.]])

In [6]:
m,n=shape(dataMatrix)
print(m,n)

100 2


In [7]:
import matplotlib.pyplot as plt
import random
import types
def smoSimple(dataMatIn, classLabels, C, toler, maxIter):
    dataMatrix = mat(dataMatIn); 
    labelMat = mat(classLabels).transpose()#将标签进行转置处理，降维为一维数组进行存储
    b = 0; 
    m,n = shape(dataMatrix)#m=100 n=2
    #初始化alpha参数，设为0  100行1列的0矩阵
    alphas = mat(zeros((m,1)))
    #初始化迭代次数，用来存储在没有任何alpha改变的情况下遍历数据集的次数
    iter_num = 0
    #最多迭代matIter次指没有任何alpha改变的情况下遍历数据集的次数
    #只有在所有数据集上遍历maxIter次，且不再发生任何alpha修改之后，程序才停止
    while (iter_num < maxIter):
        alphaPairsChanged = 0#每次循环alphaPairsChanged先设为0，用来记录alpha是否已经进行优化
        for i in range(m):#对整个集合顺序遍历
            #对于矩阵（matrix）而言，multiply是对应元素相乘  * 相当于矩阵乘法（矢量积）
            #   .T  其实就是对一个矩阵的转置
            fXi = float(multiply(alphas,labelMat).T*(dataMatrix*dataMatrix[i,:].T)) + b#我们预测的类别
            Ei = fXi - float(labelMat[i])#基于该实例的预测结果和真实结果的比对，计算误差
            #优化alpha，更设定一定的容错率。toler=0.001 C=0.6 
            if ((labelMat[i]*Ei < -toler) and (alphas[i] < C)) or ((labelMat[i]*Ei > toler) and (alphas[i] > 0)):
                j = selectJrand(i,m)
                fXj = float(multiply(alphas,labelMat).T*(dataMatrix*dataMatrix[j,:].T)) + b
                Ej = fXj - float(labelMat[j])
                #保存更新前的aplpha值，使用深拷贝 深拷贝即拷贝之后的对象不随原对象变化，即为新值分配内存
                alphaIold = alphas[i].copy()
                alphaJold = alphas[j].copy()
                #计算上下界L和H用于把alpha[j]调整到0到C之间
                if (labelMat[i] != labelMat[j]):
                    L = max(0, alphas[j] - alphas[i])
                    H = min(C, C + alphas[j] - alphas[i])
                else:
                    L = max(0, alphas[j] + alphas[i] - C)
                    H = min(C, alphas[j] + alphas[i])
                if L==H: 
                    print("L==H"); 
                    continue
                eta = 2.0 * dataMatrix[i,:]*dataMatrix[j,:].T - dataMatrix[i,:]*dataMatrix[i,:].T - dataMatrix[j,:]*dataMatrix[j,:].T
                if eta >= 0: 
                    print("eta>=0"); 
                    continue
                alphas[j] -= labelMat[j]*(Ei - Ej)/eta
                alphas[j] = clipAlpha(alphas[j],H,L)
                #判断alphas[j]是否有轻微改变，若有退出for循环
                if (abs(alphas[j] - alphaJold) < 0.00001): print("j not moving enough"); continue         
                alphas[i] += labelMat[j]*labelMat[i]*(alphaJold - alphas[j])
                b1 = b - Ei- labelMat[i]*(alphas[i]-alphaIold)*dataMatrix[i,:]*dataMatrix[i,:].T - labelMat[j]*(alphas[j]-alphaJold)*dataMatrix[i,:]*dataMatrix[j,:].T
                b2 = b - Ej- labelMat[i]*(alphas[i]-alphaIold)*dataMatrix[i,:]*dataMatrix[j,:].T - labelMat[j]*(alphas[j]-alphaJold)*dataMatrix[j,:]*dataMatrix[j,:].T
                if (0 < alphas[i]) and (C > alphas[i]): b = b1
                elif (0 < alphas[j]) and (C > alphas[j]): b = b2
                else: b = (b1 + b2)/2.0
                alphaPairsChanged += 1
                print("iter :%d, i:%d,paris changed %d" % (iter_num,i,alphaPairsChanged))
        if (alphaPairsChanged == 0): 
            iter_num += 1
        else: iter_num = 0
        print("iteration number: %d" % iter_num)
    return b,alphas,fXi


In [8]:
b,alphas,fXi= smoSimple(dataArr,labelArr,0.6,0.001,40)

L==H
iter :0, i:1,paris changed 1
iter :0, i:2,paris changed 2
iter :0, i:3,paris changed 3
L==H
L==H
L==H
iter :0, i:8,paris changed 4
j not moving enough
iter :0, i:17,paris changed 5
j not moving enough
L==H
iter :0, i:23,paris changed 6
L==H
L==H
L==H
iter :0, i:48,paris changed 7
j not moving enough
L==H
iter :0, i:53,paris changed 8
j not moving enough
L==H
L==H
j not moving enough
j not moving enough
L==H
iter :0, i:98,paris changed 9
iteration number: 0
j not moving enough
j not moving enough
iter :0, i:2,paris changed 1
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
j not moving enough
L==H
j not moving enough
iter :0, i:55,paris changed 2
j not moving enough
L==H
j not moving enough
j not moving enough
L==H
L==H
iteration number: 0
j not moving enough
j not moving enough
j not moving enough
j not moving enough
L==H
L==H
iter :0, i:15,paris changed 1
j not moving enough
j not moving en

j not moving enough
j not moving enough
j not moving enough
iteration number: 3
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 4
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 5
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 6
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 7
j not moving enough
j not moving enough
j not moving enough
iter :7, i:54,paris changed 1
iteration number: 0
iter :0, i:17,paris changed 1
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 0
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 1
j not moving enough
j not moving enough
j not moving enough
j not moving enough
iteration number: 2
j not moving enough
j not moving enough
j not moving enough
j not moving enough


j not moving enough
iteration number: 2
j not moving enough
iteration number: 3
j not moving enough
iteration number: 4
j not moving enough
iteration number: 5
j not moving enough
iteration number: 6
j not moving enough
iteration number: 7
j not moving enough
iteration number: 8
j not moving enough
iteration number: 9
j not moving enough
iteration number: 10
j not moving enough
iteration number: 11
j not moving enough
iteration number: 12
j not moving enough
iteration number: 13
j not moving enough
iteration number: 14
j not moving enough
iteration number: 15
j not moving enough
iteration number: 16
j not moving enough
iteration number: 17
j not moving enough
iteration number: 18
j not moving enough
iteration number: 19
j not moving enough
iteration number: 20
j not moving enough
iteration number: 21
j not moving enough
iteration number: 22
j not moving enough
iteration number: 23
j not moving enough
iteration number: 24
j not moving enough
iteration number: 25
j not moving enough
iter

In [9]:
print(fXi)

[[-2.34326737]]


In [10]:
print(b)

[[-3.8461176]]


In [11]:
print(alphas)

[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.13082425]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.2403074 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.37113165]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.  

In [12]:
alphas[alphas>0]

matrix([[0.13082425, 0.2403074 , 0.37113165]])

In [13]:
shape(alphas[alphas>0])

(1, 3)

In [14]:
for i in range(100):
    if alphas[i]>0.0:
        print(dataArr[i],labelArr[i])

[4.658191, 3.507396] -1
[3.457096, -0.082216] -1
[6.080573, 0.418886] 1


In [15]:
def kernelTrans(X, A, kTup):
    m,n = shape(X)
    K = mat(zeros((m,1)))
    if kTup[0]=='lin': K = X * A.T
    elif kTup[0]=='rbf':
        for j in range(m):
            deltaRow = X[j,:] - A
            K[j] = deltaRow*deltaRow.T
        K = exp(K / (-1*kTup[1]**2))
    else: raise NameError('Houston We Have a Problem -- That Kernel is not recognized')
    return K

class optStruct:
    def __init__(self,dataMatIn, classLabels, C, toler, kTup):  
        self.X = dataMatIn
        self.labelMat = classLabels
        self.C = C
        self.tol = toler
        self.m = shape(dataMatIn)[0]
        self.alphas = mat(zeros((self.m,1)))
        self.b = 0
        self.eCache = mat(zeros((self.m,2))) #first column is valid flag
        self.K = mat(zeros((self.m,self.m)))
        for i in range(self.m):
            self.K[:,i] = kernelTrans(self.X, self.X[i,:], kTup)        
        
def calcEk(oS, k):
    fXk = float(multiply(oS.alphas,oS.labelMat).T*oS.K[:,k] + oS.b)
    Ek = fXk - float(oS.labelMat[k])
    return Ek
        
def selectJ(i, oS, Ei):         
    maxK = -1; maxDeltaE = 0; Ej = 0
    oS.eCache[i] = [1,Ei] 
    validEcacheList = nonzero(oS.eCache[:,0].A)[0]
    if (len(validEcacheList)) > 1:
        for k in validEcacheList:   
            if k == i: continue
            Ek = calcEk(oS, k)
            deltaE = abs(Ei - Ek)
            if (deltaE > maxDeltaE):
                maxK = k; maxDeltaE = deltaE; Ej = Ek
        return maxK, Ej
    else:   
        j = selectJrand(i, oS.m)
        Ej = calcEk(oS, j)
    return j, Ej
def updateEk(oS, k):
    Ek = calcEk(oS, k)
    oS.eCache[k] = [1,Ek]

In [16]:
def innerL(i, oS):
    Ei = calcEk(oS, i)
    if ((oS.labelMat[i]*Ei < -oS.tol) and (oS.alphas[i] < oS.C)) or ((oS.labelMat[i]*Ei > oS.tol) and (oS.alphas[i] > 0)):
        j,Ej = selectJ(i, oS, Ei) 
        alphaIold = oS.alphas[i].copy(); alphaJold = oS.alphas[j].copy();
        if (oS.labelMat[i] != oS.labelMat[j]):
            L = max(0, oS.alphas[j] - oS.alphas[i])
            H = min(oS.C, oS.C + oS.alphas[j] - oS.alphas[i])
        else:
            L = max(0, oS.alphas[j] + oS.alphas[i] - oS.C)
            H = min(oS.C, oS.alphas[j] + oS.alphas[i])
        if L==H: print ("L==H"); return 0
        eta = 2.0 * oS.K[i,j] - oS.K[i,i] - oS.K[j,j] #changed for kernel
        if eta >= 0: print("eta>=0"); return 0
        oS.alphas[j] -= oS.labelMat[j]*(Ei - Ej)/eta
        oS.alphas[j] = clipAlpha(oS.alphas[j],H,L)
        updateEk(oS, j) #added this for the Ecache
        if (abs(oS.alphas[j] - alphaJold) < 0.00001):
            print ("j not moving enough")
            return 0
        oS.alphas[i] += oS.labelMat[j]*oS.labelMat[i]*(alphaJold - oS.alphas[j])
        updateEk(oS, i)              
        b1 = oS.b - Ei- oS.labelMat[i]*(oS.alphas[i]-alphaIold)*oS.K[i,i] - oS.labelMat[j]*(oS.alphas[j]-alphaJold)*oS.K[i,j]
        b2 = oS.b - Ej- oS.labelMat[i]*(oS.alphas[i]-alphaIold)*oS.K[i,j]- oS.labelMat[j]*(oS.alphas[j]-alphaJold)*oS.K[j,j]
        if (0 < oS.alphas[i]) and (oS.C > oS.alphas[i]): oS.b = b1
        elif (0 < oS.alphas[j]) and (oS.C > oS.alphas[j]): oS.b = b2
        else: oS.b = (b1 + b2)/2.0
        return 1
    else: return 0


In [17]:
def smoP(dataMatIn, classLabels, C, toler, maxIter,kTup=('lin', 0)):    
    oS = optStruct(mat(dataMatIn),mat(classLabels).transpose(),C,toler, kTup)
    iter = 0
    entireSet = True; alphaPairsChanged = 0
    while (iter < maxIter) and ((alphaPairsChanged > 0) or (entireSet)):
        alphaPairsChanged = 0
        if entireSet:   #go over all
            for i in range(oS.m):        
                alphaPairsChanged += innerL(i,oS)
                print ("fullSet, iter: %d i:%d, pairs changed %d" % (iter,i,alphaPairsChanged))
            iter += 1
        else:#go over non-bound (railed) alphas
            nonBoundIs = nonzero((oS.alphas.A > 0) * (oS.alphas.A < C))[0]
            for i in nonBoundIs:
                alphaPairsChanged += innerL(i,oS)
                print ("non-bound, iter: %d i:%d, pairs changed %d" % (iter,i,alphaPairsChanged))
            iter += 1
        if entireSet: entireSet = False 
        elif (alphaPairsChanged == 0): entireSet = True  
        print ("iteration number: %d" % iter)
    return oS.b,oS.alphas

In [18]:
dataArr,labelArr = loadDataSet('testSet.txt')
b,alphas = smoP(dataArr, labelArr, 0.6, 0.001, 40)

fullSet, iter: 0 i:0, pairs changed 1
fullSet, iter: 0 i:1, pairs changed 1
fullSet, iter: 0 i:2, pairs changed 1
fullSet, iter: 0 i:3, pairs changed 1
fullSet, iter: 0 i:4, pairs changed 1
fullSet, iter: 0 i:5, pairs changed 2
fullSet, iter: 0 i:6, pairs changed 2
fullSet, iter: 0 i:7, pairs changed 2
j not moving enough
fullSet, iter: 0 i:8, pairs changed 2
fullSet, iter: 0 i:9, pairs changed 2
j not moving enough
fullSet, iter: 0 i:10, pairs changed 2
fullSet, iter: 0 i:11, pairs changed 2
fullSet, iter: 0 i:12, pairs changed 2
fullSet, iter: 0 i:13, pairs changed 2
fullSet, iter: 0 i:14, pairs changed 2
fullSet, iter: 0 i:15, pairs changed 2
fullSet, iter: 0 i:16, pairs changed 2
fullSet, iter: 0 i:17, pairs changed 3
fullSet, iter: 0 i:18, pairs changed 3
fullSet, iter: 0 i:19, pairs changed 3
fullSet, iter: 0 i:20, pairs changed 3
fullSet, iter: 0 i:21, pairs changed 3
fullSet, iter: 0 i:22, pairs changed 3
fullSet, iter: 0 i:23, pairs changed 4
j not moving enough
fullSet, iter:

In [19]:
def calcWs(alphas,dataArr,classLabel):
    X = mat(dataArr)
    labelmat = mat(classLabel).transpose()
    m , n = shape(X)
    w = zeros((n,1))
    for i  in range(m):
        w += multiply(alphas[i]*labelmat[i],X[i,:].T)
    return w

In [20]:
ws = calcWs(alphas,dataArr,labelArr)
print(ws)

[[ 0.78035089]
 [-0.23667783]]


In [21]:
datamat = mat(dataArr)
datamat[2]*mat(ws)+b


matrix([[2.62094609]])

In [22]:
labelArr[2]

1

In [23]:
from sklearn.datasets import make_blobs
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import numpy as np

In [24]:
blobos = make_blobs

In [25]:
X,y = make_blobs(n_samples=50, centers=2, random_state=0,cluster_std=0.6)

In [26]:
dataArr=X

In [27]:
labelArr=y

In [28]:
len(y)

50

In [29]:
for i in range(50):
    if y[i] == 0:
        y[i] = -1

In [30]:
y

array([ 1,  1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1, -1, -1,
        1, -1, -1,  1,  1,  1,  1,  1, -1, -1, -1,  1, -1,  1, -1, -1, -1,
       -1,  1,  1, -1,  1, -1,  1, -1,  1,  1, -1,  1,  1, -1,  1, -1])

In [31]:
b,alphas = smoP(dataArr, labelArr, 0.6, 0.001, 40)

L==H
fullSet, iter: 0 i:0, pairs changed 0
fullSet, iter: 0 i:1, pairs changed 1
fullSet, iter: 0 i:2, pairs changed 2
fullSet, iter: 0 i:3, pairs changed 3
fullSet, iter: 0 i:4, pairs changed 3
fullSet, iter: 0 i:5, pairs changed 3
fullSet, iter: 0 i:6, pairs changed 3
fullSet, iter: 0 i:7, pairs changed 4
fullSet, iter: 0 i:8, pairs changed 4
fullSet, iter: 0 i:9, pairs changed 4
fullSet, iter: 0 i:10, pairs changed 4
fullSet, iter: 0 i:11, pairs changed 4
fullSet, iter: 0 i:12, pairs changed 4
fullSet, iter: 0 i:13, pairs changed 4
L==H
fullSet, iter: 0 i:14, pairs changed 4
L==H
fullSet, iter: 0 i:15, pairs changed 4
j not moving enough
fullSet, iter: 0 i:16, pairs changed 4
fullSet, iter: 0 i:17, pairs changed 4
L==H
fullSet, iter: 0 i:18, pairs changed 4
fullSet, iter: 0 i:19, pairs changed 4
fullSet, iter: 0 i:20, pairs changed 4
fullSet, iter: 0 i:21, pairs changed 4
fullSet, iter: 0 i:22, pairs changed 4
fullSet, iter: 0 i:23, pairs changed 4
fullSet, iter: 0 i:24, pairs chang

In [32]:
def calcWs(alphas,dataArr,classLabel):
    X = mat(dataArr)
    labelmat = mat(classLabel).transpose()
    m , n = shape(X)
    w = zeros((n,1))
    for i  in range(m):
        w += multiply(alphas[i]*labelmat[i],X[i,:].T)
    return w

In [33]:
ws = calcWs(alphas,dataArr,labelArr)
print(ws)

[[ 0.50645357]
 [-1.03005818]]


In [34]:
datamat = mat(dataArr)
datamat[2]*mat(ws)+b

matrix([[-1.79836925]])

In [35]:
labelArr[5]

1