In [1]:
def loadDataSet():
    postingList =[['my','dog','has','flea','problems','help','please'],
                  ['maybe','not','take','him','to','dog','parl','stupid'],
                  ['my','dalmtion','is','so','cute','I','love','him'],
                  ['stop','posting','stupid','worthless','garbage'],
                  ['mr','licks','ate','my','steak','how','to','stop','him'],
                  ['quit','buying','worthless','dog','food','stupid']]
    classVec=[0,1,0,1,0,1]
    return postingList,classVec
def createVocabList(dataSet):
    vocabSet = set([])
    for document in dataSet:
        vocabSet = vocabSet | set(document)
    return list(vocabSet)
def setOfWords2vec(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] = 1
        else :print('the word: %s is not  in my  Vacobulary!' %word)
    return returnVec

In [2]:
listOPosts,listClasses = loadDataSet()
myVocabList = createVocabList(listOPosts)

In [3]:
myVocabList

['stop',
 'so',
 'how',
 'my',
 'I',
 'quit',
 'stupid',
 'licks',
 'is',
 'posting',
 'ate',
 'to',
 'problems',
 'not',
 'him',
 'maybe',
 'love',
 'steak',
 'worthless',
 'garbage',
 'has',
 'mr',
 'flea',
 'buying',
 'help',
 'dog',
 'food',
 'parl',
 'dalmtion',
 'please',
 'take',
 'cute']

In [4]:
setOfWords2vec(myVocabList, listOPosts[0])

[0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0]

In [5]:
setOfWords2vec(myVocabList, listOPosts[3])

[1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [6]:
from numpy import *
import operator
def trainNB0(trainMatrix, trainCategory):
    numTrainDoces = len(trainMatrix)
    numWrods = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDoces)
    p0Num = ones(numWrods)
    p1Num = ones(numWrods)
    p0Denom = 2.0; p1Denom = 2.0
    for i in range(numTrainDoces):
        if trainCategory[i] ==1:
            p1Num += trainMatrix[i]
            p1Denom +=sum(trainMatrix[i])
        else :
            p0Num +=trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = log(p1Num/p1Denom)
    p0Vect = log(p0Num/p0Denom)
    return p0Vect,p1Vect,pAbusive

In [7]:
from numpy import *
import operator
def trainNB0(trainMatrix, trainCategory):
    numTrainDoces = len(trainMatrix)
    numWrods = len(trainMatrix[0])
    pAbusive = sum(trainCategory)/float(numTrainDoces)
    p0Num = zeros(numWrods)
    p1Num = zeros(numWrods)
    p0Denom = 2.0; p1Denom = 2.0
    for i in range(numTrainDoces):
        if trainCategory[i] ==1:
            p1Num += trainMatrix[i]
            p1Denom +=sum(trainMatrix[i])
        else :
            p0Num +=trainMatrix[i]
            p0Denom += sum(trainMatrix[i])
    p1Vect = p1Num/p1Denom
    p0Vect = p0Num/p0Denom
    return p0Vect,p1Vect,pAbusive

In [8]:
listOPosts,listClasses = loadDataSet()
myVocabList = createVocabList(listOPosts)

In [9]:
trainMat= []
for postinDoc in listOPosts:
    trainMat.append(setOfWords2vec(myVocabList, postinDoc))

In [10]:
trainMat

[[0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0],
 [0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1],
 [1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [1,
  0,
  1,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0]]

In [11]:
print(len(trainMat))
print(len(trainMat[0]))

6
32


In [12]:
array(trainMat)

array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 0, 0, 0, 0]])

In [13]:
p0V,p1V,pAb=trainNB0(trainMat,listClasses)

In [14]:
pAb

0.5

In [15]:
p0V

array([0.03846154, 0.03846154, 0.03846154, 0.11538462, 0.03846154,
       0.        , 0.        , 0.03846154, 0.03846154, 0.        ,
       0.03846154, 0.03846154, 0.03846154, 0.        , 0.07692308,
       0.        , 0.03846154, 0.03846154, 0.        , 0.        ,
       0.03846154, 0.03846154, 0.03846154, 0.        , 0.03846154,
       0.03846154, 0.        , 0.        , 0.03846154, 0.03846154,
       0.        , 0.03846154])

In [16]:
array(setOfWords2vec(myVocabList, listOPosts[3]))

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
sum(array(setOfWords2vec(myVocabList, listOPosts[3]))*p0V)+log(pAb)

-0.6546856420984069

In [18]:
p1V

array([0.04761905, 0.        , 0.        , 0.        , 0.        ,
       0.04761905, 0.14285714, 0.        , 0.        , 0.04761905,
       0.        , 0.04761905, 0.        , 0.04761905, 0.04761905,
       0.04761905, 0.        , 0.        , 0.0952381 , 0.04761905,
       0.        , 0.        , 0.        , 0.04761905, 0.        ,
       0.0952381 , 0.04761905, 0.04761905, 0.        , 0.        ,
       0.04761905, 0.        ])

In [19]:
def classifyNB(vec2Classify, p0Vec, p1Vec,pClass1):
    p1 = sum(vec2Classify * p1Vec) + log(pClass1)
    p0 = sum(vec2Classify * p0Vec) + log(1.0 - pClass1)
    if p1 > p0 :
        return 1
    else :
        return 0
def testingNB():
    listOPost,listClasses = loadDataSet()
    myVocabList = createVocabList(listOPosts)
    trainMat=[]
    for postinDoc in listOPosts:
        trainMat.append(setOfWords2vec(myVocabList,postinDoc))
    p0V,p1V,pAb =trainNB0(array(trainMat),array(listClasses))
    testEntry = ['love','my','garbage']
    thisDoc = array(setOfWords2vec(myVocabList, testEntry))
    print(testEntry,'classified as:',classifyNB(thisDoc, p0V,p1V,pAb))
    testEntry = ['stupid','grabage']
    thisDoc = array(setOfWords2vec(myVocabList, testEntry))
    print(testEntry,'classified as:',classifyNB(thisDoc, p0V,p1V,pAb))

In [20]:
testingNB()

['love', 'my', 'garbage'] classified as: 0
the word: grabage is not  in my  Vacobulary!
['stupid', 'grabage'] classified as: 1


In [21]:
def bagOfWords2VecMN(vocabList, inputSet):
    returnVec = [0]*len(vocabList)
    for word in inputSet:
        if word in vocabList:
            returnVec[vocabList.index(word)] +=1
    return returnVec

In [22]:
import re
def textParse(bigString):    #input is big string, #output is word list
    listOfTokens = re.split(r'/\W*', bigString)
    return [tok.lower() for tok in listOfTokens if len(tok) > 2]

In [23]:
wordList = textParse(open('email/spam/1.txt' ).read())
print(wordList)

['--- codeine 15mg -- 30 for $203.70 -- visa only!!! --\n\n-- codeine (methylmorphine) is a narcotic (opioid) pain reliever\n-- we have 15mg & 30mg pills -- 30', '15mg for $203.70 - 60', '15mg for $385.80 - 90', '15mg for $562.50 -- visa only!!! ---']


In [24]:
def spamTest():
    docList=[]
    classList = []
    fullText =[]
    for i in range(1,26):
        wordList = textParse(open('email/spam/%d.txt' % i).read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(1)
        wordList = textParse(open('email/ham/%d.txt' % i).read())
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(0)
    vocabList = createVocabList(docList)
    print(docList[5])
    trainingSet = list(range(50)); testSet=[]          
    for i in range(10):
        randIndex = int(random.uniform(0,len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])  
    trainMat=[]; trainClasses = []
    for docIndex in testSet:
        trainMat.append(bagOfWords2VecMN(vocabList, docList[docIndex]))
        trainClasses.append(classList[docIndex])
    p0V,p1V,pSpam = trainNB0(array(trainMat),array(trainClasses))
    errorCount = 0
    for docIndex in testSet:       
        wordVector = bagOfWords2VecMN(vocabList, docList[docIndex])
        if classifyNB(array(wordVector),p0V,p1V,pSpam) != classList[docIndex]:
            errorCount += 1
            print ("classification error",docList[docIndex])
    print ('the error rate is: ',float(errorCount)/len(testSet))

In [25]:
spamTest()

["what is going on there?\ni talked to john on email.  we talked about some computer stuff that's it.\n\ni went bike riding in the rain, it was not that cold.\n\nwe went to the museum in sf yesterday it was $3 to get in and they had\nfree food.  at the same time was a sf giants game, when we got done we\nhad to take the train with all the giants fans, they are 1", '2 drunk.']
classification error ["i've thought about this and think it's possible. we should get another\nlunch. i have a car now and could come pick you up this time. does\nthis wednesday work? 11:50?\n\ncan i have a signed copy of you book?"]
classification error ['hi peter,\n\nwith jose out of town, do you want to\nmeet once in a while to keep things\ngoing and do some interesting stuff?\n\nlet me know\neugene']
the error rate is:  0.2


In [26]:
import feedparser
ny=feedparser.parse('http://newyork.craigslist.org/stp/index.rss')

ModuleNotFoundError: No module named 'feedparser'

In [27]:
ny['entries']
len(ny['entries'])

NameError: name 'ny' is not defined

In [28]:
def calcMostFreq(vocabList,fullText):
    import feedparser
    import operator
    freqDict = {}
    for token in vocabList:
        freqDict[token]=fullText.count(token)
        sortedFreq = sorted(freqDict.iteritems(), key=operator.itemgetter(1), reverse=True) 
        return sortedFreq[:30]        
def localWords(feed1,feed0):
    import feedparser
    docList=[]; classList = []; fullText =[]
    minLen = min(len(feed1['entries']),len(feed0['entries']))
    for i in range(minLen):
        wordList = textParse(feed1['entries'][i]['summary'])
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(1) #NY is class 1
        wordList = textParse(feed0['entries'][i]['summary'])
        docList.append(wordList)
        fullText.extend(wordList)
        classList.append(0)
    vocabList = createVocabList(docList)#create vocabular
    top30Words = calcMostFreq(vocabList,fullText)   #remove top 30 words
    for pairW in top30Words:
        if pairW[0] in vocabList: vocabList.remove(pairW[0])
    trainingSet = range(2*minLen); testSet=[]           #create test set
    for i in range(20):
        randIndex = int(random.uniform(0,len(trainingSet)))
        testSet.append(trainingSet[randIndex])
        del(trainingSet[randIndex])  
    trainMat=[]; trainClasses = []
    for docIndex in trainingSet:#train the classifier (get probs) trainNB0
        trainMat.append(bagOfWords2VecMN(vocabList, docList[docIndex]))
        trainClasses.append(classList[docIndex])
    p0V,p1V,pSpam = trainNB0(array(trainMat),array(trainClasses))
    errorCount = 0
    for docIndex in testSet:        #classify the remaining items
        wordVector = bagOfWords2VecMN(vocabList, docList[docIndex])
        if classifyNB(array(wordVector),p0V,p1V,pSpam) != classList[docIndex]:
            errorCount += 1
    print ('the error rate is: ',float(errorCount)/len(testSet))
    return vocabList,p0V,p1V

In [29]:
range(10)
print(range(10))
help(range)

range(0, 10)
Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash_

In [30]:
ss=[0]*20

In [31]:
ss

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [56]:
print(range(50))

range(0, 50)


In [54]:
print(len(range(50)))

50
